### ISSUE TITLE
作者你好，脚本在我的服务器上不能使用

### ISSUE THREAD

**Issue by Arturia169** [uxh/superspeed#1]
# 服务器发行版：Debian 11
> 测速选项：3 电信测速
> 测试时间2022-10-28日
***
失效截图
![image](https://user-images.githubusercontent.com/69199123/198593888-b1390c3c-2792-438b-8786-340c8e76dd41.png)
***

**Comment by uxh** [comment]
麻烦执行脚本时，加上`-x`参数，再截图看下。
例如`bash -x shell.sh`

**Comment by Arturia169** [comment]
> 

# 控制台输出
***
> root@chao14:~# bash -x <(curl -Lso- https://git.io/superspeed_uxh)
+ RED='\033[0;31m'
+ GREEN='\033[0;32m'
+ YELLOW='\033[0;33m'
+ BLUE='\033[0;34m'
+ PURPLE='\033[0;35m'
+ CYAN='\033[0;36m'
+ PLAIN='\033[0m'
+ runall
+ checkroot
+ [[ 0 -ne 0 ]]
+ checksystem
+ '[' -f /etc/redhat-release ']'
+ grep -Eqi debian
+ cat /etc/issue
+ release=debian
+ checkpython
+ '[' '!' -e /usr/bin/python ']'
+ checkcurl
+ '[' '!' -e /usr/bin/curl ']'
+ checkwget
+ '[' '!' -e /usr/bin/wget ']'
+ speed_test
+ speedLog=./speedtest.log
+ true
+ speedtest-cli/speedtest -p no -s --accept-license --accept-gdpr
++ grep Upload
++ cat ./speedtest.log
+ is_upload=
+ [[ -n '' ]]
+ local cerror=ERROR
+ preinfo
+ echo ——————————————————————————————————————————————————————————
——————————————————————————————————————————————————————————
+ echo ' SuperSpeed 全面测速修复版. By UXH & ernisn & oooldking'
 SuperSpeed 全面测速修复版. By UXH & ernisn & oooldking
+ echo ' 节点更新: 2020/06/19 | 脚本更新: 2021/12/23'
 节点更新: 2020/06/19 | 脚本更新: 2021/12/23
+ echo ' Github: https://github.com/uxh/superspeed'
 Github: https://github.com/uxh/superspeed
+ echo ——————————————————————————————————————————————————————————
——————————————————————————————————————————————————————————
+ selecttest
+ echo -e '  测速类型:    \033[0;32m0.\033[0m 取消测速    \033[0;32m1.\033[0m 三网测速    \033[0;32m2.\033[0m 详细测速'
  测速类型:    0. 取消测速    1. 三网测速    2. 详细测速
+ echo -ne '               \033[0;32m3.\033[0m 电信节点    \033[0;32m4.\033[0m 联通节点    \033[0;32m5.\033[0m 移动节点'
               3. 电信节点    4. 联通节点    5. 移动节点+ :
+ echo

+ read -p '  请输入数字选择测速类型: ' selection
  请输入数字选择测速类型: 3
+ [[ ! 3 =~ ^[1-5]$ ]]
+ break
+ runtest
+ [[ 3 == 0 ]]
+ [[ 3 == 1 ]]
+ [[ 3 == 2 ]]
+ [[ 3 == 3 ]]
+ echo ——————————————————————————————————————————————————————————
——————————————————————————————————————————————————————————
+ echo 'ID    测速服务器信息       上传/Mbps   下载/Mbps   延迟/ms'
ID    测速服务器信息       上传/Mbps   下载/Mbps   延迟/ms
++ date +%s
+ start=1667103291
+ speed_test 3633 上海 电信
+ speedLog=./speedtest.log
+ true
+ speedtest-cli/speedtest -p no -s 3633 --accept-license --accept-gdpr
++ grep Upload
++ cat ./speedtest.log
+ is_upload=
+ [[ -n '' ]]
+ local cerror=ERROR
+ speed_test 24012 内蒙古呼和浩特 电信
+ speedLog=./speedtest.log
+ true
+ speedtest-cli/speedtest -p no -s 24012 --accept-license --accept-gdpr
++ grep Upload
++ cat ./speedtest.log
+ is_upload=
+ [[ -n '' ]]
+ local cerror=ERROR
+ speed_test 27377 北京５Ｇ 电信
+ speedLog=./speedtest.log
+ true
+ speedtest-cli/speedtest -p no -s 27377 --accept-license --accept-gdpr
++ grep Upload
++ cat ./speedtest.log
+ is_upload=
+ [[ -n '' ]]
+ local cerror=ERROR
+ speed_test 29026 四川成都 电信
+ speedLog=./speedtest.log
+ true
+ speedtest-cli/speedtest -p no -s 29026 --accept-license --accept-gdpr
++ grep Upload
++ cat ./speedtest.log
+ is_upload=
+ [[ -n '' ]]
+ local cerror=ERROR
+ speed_test 29071 四川成都 电信
+ speedLog=./speedtest.log
+ true
+ speedtest-cli/speedtest -p no -s 29071 --accept-license --accept-gdpr
++ grep Upload
++ cat ./speedtest.log
+ is_upload=
+ [[ -n '' ]]
+ local cerror=ERROR
+ speed_test 17145 安徽合肥５Ｇ 电信
+ speedLog=./speedtest.log
+ true
+ speedtest-cli/speedtest -p no -s 17145 --accept-license --accept-gdpr
++ grep Upload
++ cat ./speedtest.log
+ is_upload=
+ [[ -n '' ]]
+ local cerror=ERROR
+ speed_test 27594 广东广州５Ｇ 电信
+ speedLog=./speedtest.log
+ true
+ speedtest-cli/speedtest -p no -s 27594 --accept-license --accept-gdpr
++ grep Upload
++ cat ./speedtest.log
+ is_upload=
+ [[ -n '' ]]
+ local cerror=ERROR
+ speed_test 27810 广西南宁 电信
+ speedLog=./speedtest.log
+ true
+ speedtest-cli/speedtest -p no -s 27810 --accept-license --accept-gdpr
++ grep Upload
++ cat ./speedtest.log
+ is_upload=
+ [[ -n '' ]]
+ local cerror=ERROR
+ speed_test 27575 新疆乌鲁木齐 电信
+ speedLog=./speedtest.log
+ true
+ speedtest-cli/speedtest -p no -s 27575 --accept-license --accept-gdpr
++ grep Upload
++ cat ./speedtest.log
+ is_upload=
+ [[ -n '' ]]
+ local cerror=ERROR
+ speed_test 26352 江苏南京５Ｇ 电信
+ speedLog=./speedtest.log
+ true
+ speedtest-cli/speedtest -p no -s 26352 --accept-license --accept-gdpr
++ grep Upload
++ cat ./speedtest.log
+ is_upload=
+ [[ -n '' ]]
+ local cerror=ERROR
+ speed_test 5396 江苏苏州５Ｇ 电信
+ speedLog=./speedtest.log
+ true
+ speedtest-cli/speedtest -p no -s 5396 --accept-license --accept-gdpr
++ grep Upload
++ cat ./speedtest.log
+ is_upload=
+ [[ -n '' ]]
+ local cerror=ERROR
+ speed_test 5317 江苏连云港５Ｇ 电信
+ speedLog=./speedtest.log
+ true
+ speedtest-cli/speedtest -p no -s 5317 --accept-license --accept-gdpr
++ grep Upload
++ cat ./speedtest.log
+ is_upload=
+ [[ -n '' ]]
+ local cerror=ERROR
+ speed_test 36663 江苏镇江５Ｇ 电信
+ speedLog=./speedtest.log
+ true
+ speedtest-cli/speedtest -p no -s 36663 --accept-license --accept-gdpr
++ cat ./speedtest.log
++ grep Upload
+ is_upload=
+ [[ -n '' ]]
+ local cerror=ERROR
+ speed_test 7509 浙江杭州 电信
+ speedLog=./speedtest.log
+ true
+ speedtest-cli/speedtest -p no -s 7509 --accept-license --accept-gdpr
++ grep Upload
++ cat ./speedtest.log
+ is_upload=
+ [[ -n '' ]]
+ local cerror=ERROR
+ speed_test 23844 湖北武汉 电信
+ speedLog=./speedtest.log
+ true
+ speedtest-cli/speedtest -p no -s 23844 --accept-license --accept-gdpr
++ grep Upload
++ cat ./speedtest.log
+ is_upload=
+ [[ -n '' ]]
+ local cerror=ERROR
+ speed_test 29353 湖北武汉５Ｇ 电信
+ speedLog=./speedtest.log
+ true
+ speedtest-cli/speedtest -p no -s 29353 --accept-license --accept-gdpr
++ grep Upload
++ cat ./speedtest.log
+ is_upload=
+ [[ -n '' ]]
+ local cerror=ERROR
+ speed_test 28225 湖南长沙５Ｇ 电信
+ speedLog=./speedtest.log
+ true
+ speedtest-cli/speedtest -p no -s 28225 --accept-license --accept-gdpr
++ grep Upload
++ cat ./speedtest.log
+ is_upload=
+ [[ -n '' ]]
+ local cerror=ERROR
+ speed_test 3973 甘肃兰州 电信
+ speedLog=./speedtest.log
+ true
+ speedtest-cli/speedtest -p no -s 3973 --accept-license --accept-gdpr
++ grep Upload
++ cat ./speedtest.log
+ is_upload=
+ [[ -n '' ]]
+ local cerror=ERROR
+ speed_test 19076 重庆 电信
+ speedLog=./speedtest.log
+ true
+ speedtest-cli/speedtest -p no -s 19076 --accept-license --accept-gdpr
++ grep Upload
++ cat ./speedtest.log
+ is_upload=
+ [[ -n '' ]]
+ local cerror=ERROR
+ speed_test 35722 天津 电信
+ speedLog=./speedtest.log
+ true
+ speedtest-cli/speedtest -p no -s 35722 --accept-license --accept-gdpr
++ grep Upload
++ cat ./speedtest.log
+ is_upload=
+ [[ -n '' ]]
+ local cerror=ERROR
+ speed_test 34115 天津５Ｇ 电信
+ speedLog=./speedtest.log
+ true
+ speedtest-cli/speedtest -p no -s 34115 --accept-license --accept-gdpr
++ grep Upload
++ cat ./speedtest.log
+ is_upload=
+ [[ -n '' ]]
+ local cerror=ERROR
+ speed_test 41355 河南郑州５Ｇ 电信
+ speedLog=./speedtest.log
+ true
+ speedtest-cli/speedtest -p no -s 41355 --accept-license --accept-gdpr
++ grep Upload
++ cat ./speedtest.log
+ is_upload=
+ [[ -n '' ]]
+ local cerror=ERROR
+ speed_test 34988 辽宁沈阳５Ｇ 电信
+ speedLog=./speedtest.log
+ true
+ speedtest-cli/speedtest -p no -s 34988 --accept-license --accept-gdpr
++ grep Upload
++ cat ./speedtest.log
+ is_upload=
+ [[ -n '' ]]
+ local cerror=ERROR
++ date +%s
+ end=1667103346
+ rm -rf speedtest-cli speedtest.log speedtest.tgz
+ echo ——————————————————————————————————————————————————————————
——————————————————————————————————————————————————————————
+ time=55
+ [[ 55 -gt 60 ]]
+ echo -ne '  测试完成, 本次测速耗时: 55 秒'
  测试完成, 本次测速耗时: 55 秒+ echo -ne '\n  当前时间: '

  当前时间: ++ TZ=UTC-8
++ date '+%Y-%m-%d %H:%M:%S'
+ echo 2022-10-30 12:15:46
2022-10-30 12:15:46
+ [[ 3 == 4 ]]
+ [[ 3 == 5 ]]
+ rm -rf 'speedtest*'
***

**Comment by ming019** [comment]
Same error occured when test using my home router.
